version: '3.8'

services:
  # Organization runner example
  github-runner-org:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-runner-org-podman
    # env_file: 
    #   - .env
    secrets:
      - runner_token_secret
    environment:
      # For organization runners - use ORG_URL
      ORG_URL: https://github.com/isri-aist
      # Optional organization-specific settings
      RUNNER_NAME: isri-aist-podman-runner-01
      RUNNER_GROUP: Default
      RUNNER_LABELS: ubuntu-22.04,podman,self-hosted,organization,production
      RUNNER_WORKDIR: _work
      # RUNNER_TOKEN is set using echo "***" | podman secret create runner_token_secret -
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - org-runner-work:/home/runner/_work
      - org-podman-storage:/home/runner/.local/share/containers
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 40G
          cpus: '16'

  # # Repository runner example (optional - can run both)
  # github-runner-repo:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: github-runner-repo-podman
  #   environment:
  #     # For repository runners - use REPO_URL
  #     - REPO_URL=https://github.com/your-organization/your-repo
  #     - RUNNER_TOKEN=your_repo_runner_token_here
  #     
  #     # Optional repository-specific settings
  #     - RUNNER_NAME=repo-podman-runner-01
  #     - RUNNER_LABELS=ubuntu-22.04,podman,self-hosted,repository,staging
  #     - RUNNER_WORKDIR=_work
  #     
  #   user: "1000:1000"
  #   volumes:
  #     - repo-runner-work:/home/runner/_work
  #     - repo-podman-storage:/home/runner/.local/share/containers
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 2G
  #         cpus: '1'

secrets:
 runner_token_secret:
   external: true
volumes:
  org-runner-work:
    driver: local
  org-podman-storage:
    driver: local
  repo-runner-work:
    driver: local
  repo-podman-storage:
    driver: local
